In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.datasets import load_digits
digits = load_digits()

In [2]:
# X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [3]:
lr = LogisticRegression(max_iter=10000)
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

NameError: name 'X_train' is not defined

In [ ]:
svm = SVC(kernel='rbf',C=100)
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

In [ ]:
rf = RandomForestClassifier(n_estimators=1000)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

In [6]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [7]:
for train, test in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train,test)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [8]:
def score(model,x_train,y_train,x_test,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [30]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=3)
lr = []
svc = []
rf = []

for train_index,test_index in skf.split(digits.data,digits.target):
    x_train,x_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    lr.append(score(LogisticRegression(max_iter=1000),x_train,y_train,x_test,y_test))
    svc.append(score(SVC(kernel="rbf",C=10),x_train,y_train,x_test,y_test))
    rf.append(score(RandomForestClassifier(n_estimators=100),x_train,y_train,x_test,y_test))


In [33]:
print([lr,svc,rf])

[[0.9198664440734557, 0.9415692821368948, 0.9165275459098498], [0.9682804674457429, 0.9799666110183639, 0.9732888146911519], [0.9432387312186978, 0.9682804674457429, 0.9265442404006677]]


In [46]:
from sklearn.model_selection import cross_val_score
def cvs(model):
    return cross_val_score(model,digits.data,digits.target,cv=4)

In [57]:
a=[cvs(LogisticRegression(max_iter=1000))]
# cvs(SVC(kernel="rbf",C=100)),
# cvs(RandomForestClassifier(n_estimators=100))]
a

[array([0.93555556, 0.9064588 , 0.95100223, 0.91759465])]

In [55]:
np.average(a)

np.float64(0.9276528087107152)

In [44]:
cross_val_score(LogisticRegression(max_iter=1000),digits.data,digits.target,cv=4)

array([0.93555556, 0.9064588 , 0.95100223, 0.91759465])